project_id = "rfuflyhitqwxtcecllya"

[functions.ai-search]
verify_jwt = false

[functions.scrape-news]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false

[functions.compare-stocks]
verify_jwt = false

[functions.get-stock-prices]
verify_jwt = false
